language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - npm run build

before_install:
  - printf "@fortawesome:registry=https://registry.fortawesome.com/\n//registry.fortawesome.com/:_authToken=${FA_TOKEN}" >> ~/.npmrc

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
