language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm run deploy
  
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master

notifications:
  email:
    on_failure: change