language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    committer-from-gh: true

notifications:
  email:
    on_failure: change