language: node_js

node_js:
  - 'stable'

before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/"//npm.fontawesome.com/:_authToken=\${FA_TOKEN}"

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
