language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - npm run build

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${FA_TOKEN}"

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
