language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

before_install:
  - echo @fortawesome:registry=https://npm.fontawesome.com/ >> .npmrc
  - echo //npm.fontawesome.com/:_authToken=$FA_TOKEN >> .npmrc

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master

notifications:
  email:
    on_failure: change
